//<![CDATA[
function removeHtmlTag(e,f){if(e.indexOf("<")!=-1){var g=e.split("<");for(var h=0;h<g.length;h++){if(g[h].indexOf(">")!=-1){g[h]=g[h].substring(g[h].indexOf(">")+1,g[h].length)}}e=g.join("")}f=(f<e.length-1)?f:e.length-2;while(e.charAt(f-1)!=" "&&e.indexOf(" ",f)!=-1){f++}e=e.substring(0,f-1);return e+"..."}function createSummaryAndThumb(k){var i=document.getElementById(k);var h="";var g=i.getElementsByTagName("img");var j=summary_noimg;if(g.length>=1){h='<span style="display:none;float:left;margin:0px 10px 5px 0px;"><img src="'+g[0].src+'" width="'+img_thumb_width+'px" height="'+img_thumb_height+'px"/></span>';j=summary_img}var l=h+"<div>"+removeHtmlTag(i.innerHTML,j)+"</div>";i.innerHTML=l};

//recent
function labelthumbs(t){document.write('<ul class="label_with_thumbs">');for(var e=0;e<numposts;e++){var r,n=t.feed.entry[e],i=n.title.$t;if(e==t.feed.entry.length)break;for(var m=0;m<n.link.length;m++){if("replies"==n.link[m].rel&&"text/html"==n.link[m].type)var o=n.link[m].title,l=n.link[m].href;if("alternate"==n.link[m].rel){r=n.link[m].href;break}}var u;try{u=n.media$thumbnail.url}catch(h){s=n.content.$t,a=s.indexOf("<img"),b=s.indexOf('src="',a),c=s.indexOf('"',b+5),d=s.substr(b+5,c-b-5),u=-1!=a&&-1!=b&&-1!=c&&""!=d?d:"https://4.bp.blogspot.com/-ZnmA8zuzBAs/WBaZ1rP0-9I/AAAAAAAACKY/XnKsWWmEaCMx_-Wk-nSJxiHfwVxZniicQCLcB/s1600/noimage.jpg"}var f=n.published.$t,p=f.substring(0,4),w=f.substring(5,7),g=f.substring(8,10),v=new Array;if(v[1]="Jan",v[2]="Feb",v[3]="Mar",v[4]="Apr",v[5]="May",v[6]="Jun",v[7]="Jul",v[8]="Aug",v[9]="Sep",v[10]="Oct",v[11]="Nov",v[12]="Dec",document.write('<li class="clearfix">'),1==showpostthumbnails&&document.write('<a href="'+r+'" target ="_top"><img class="label_thumb" src="'+u+'"/></a>'),document.write('<strong><a href="'+r+'" target ="_top">'+i+"</a></strong><br>"),"content"in n)var A=n.content.$t;else if("summary"in n)var A=n.summary.$t;else var A="";var y=/<\S[^>]*>/g;if(A=A.replace(y,""),1==showpostsummary)if(A.length<numchars)document.write(""),document.write(A),document.write("");else{document.write(""),A=A.substring(0,numchars);var k=A.lastIndexOf(" ");A=A.substring(0,k),document.write(A+"..."),document.write("")}var x="",_=0;document.write("<br>"),1==showpostdate&&(x=x+v[parseInt(w,10)]+"-"+g+" - "+p,_=1),1==showcommentnum&&(1==_&&(x+=" | "),"1 Comments"==o&&(o="1 Comment"),"0 Comments"==o&&(o="No Comments"),o='<a href="'+l+'" target ="_top">'+o+"</a>",x+=o,_=1),1==displaymore&&(1==_&&(x+=" | "),x=x+'<a href="'+r+'" class="url" target ="_top">More »</a>',_=1),document.write(x),document.write("</li>"),1==displayseparator&&e!=numposts-1&&document.write("")}document.write("</ul>")}

var no_image = "https://4.bp.blogspot.com/-ZnmA8zuzBAs/WBaZ1rP0-9I/AAAAAAAACKY/XnKsWWmEaCMx_-Wk-nSJxiHfwVxZniicQCLcB/s1600/noimage.jpg";
var month_format = [, "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sept", "Oct", "Nov", "Dec"];
var more_text = "View More";
var related_number = 3;
var comments_text = "<span>Post </span>Comment";
var pagenav_prev = "Previous";
var pagenav_next = "Next";
